# Generated by Django 4.2.5 on 2023-09-11 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_feed', '0002_alter_codemodel_author_alter_codemodel_bookmarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codemodel',
            name='problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='code_feed.problemmodel'),
        ),
    ]
